TODO:
    java.lang.SecurityException: Permission Denial: reading androidx.core.content.FileProvider uri content://com.example.watermelonh.provider/external_files/Android/data/com.example.watermelonh/files/Watermelon_Images from pid=15143, uid=10115 requires the provider be exported, or grantUriPermission()

Fix this.